### PR TITLE
[MRG] Cnn module resolves #220

### LINKED ISSUE #220: Isolate CNN architecture search into a class
### Feature Description
It may be useful to isolate CNN architecture search, train function into a separate class. 

### Reason
Some image classification task may not be able to apply ImageClassifier class due to different data preprocessing needed. Furthermore, by separating CNN architecture from task module, users can define their own task module such as VideoClassifier more easily. 

### Solution
Introduce a CnnArchitecture class with method like search_best_model, train, get_model. Remove search related function from image_supervised.py. ImageClassifier should call CnnArchutecture to search for best model and train and so on.

### Alternative Solutions
If data preprocessing is the only dilemma motivating us to develop such a structure. And no CnnArchitecture reuse need in the near future. Then we probably should just introduce DataTransformer as a parameter in initializing the ImageClassifier class to let users define the custom DataTransformer?

### Additional Context
Any suggestion will be much appreciated.

### PR DESCRIPTION
**Pull request by tl-yang**
This pull request resolves #220.

The pull request is in progress.

The details of the pull request:

### CODE REVIEW

**Comment by jhfjhfj1** [comment]
@tl-yang Is this one ready to merge?
If so, please request code review, change assignee, and, change the [WIP] to [MRG].

**Comment by tl-yang** [comment]
@jhfjhfj1  I'll test this a little bit more. I found something unexpected process closing error.

**Comment by jhfjhfj1** [comment]
Sure. Thanks! @tl-yang

**Comment by tl-yang** [comment]
@jhfjhfj1 I think this pr is ready to be merged. How do you think?

**Pull request merged**
